name: Python application with CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python -m unittest test_senha.py
    - name: Package project
      run: zip -r senha.zip .
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: senha-artifact
        path: senha.zip